name: PlatformIO Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Pio
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: python -m pip install --upgrade platformio

      - name: Run PlatformIO Build
        run: pio run -e esp32c3

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32c3-firmware
          path: .pio/build/esp32c3/*.bin
